fedora-infra/the-new-hotness

fedmsg.d/hotness-example.py
hotness/anitya.py
hotness/consumers.py

This should be the last missing piece we need before we can deploy
the-new-hotness.
It watches for new packages being added to Fedora (after they've gone
through review, when they get added to pkgdb), and then it checks to see if
any projects are registered in anitya with the same upstream_url.
If none exist, then it adds the new project with the best guess it can at
the backend and it maps the project to the new Fedora package.
We map the package if the project already exists.
Also, this publishes new fedmsg messages about success and failure.
The new fedmsg messages will require a new entry in the fedmsg.meta module to
handle them.
Lastly, this requires that a new release of release-monitoring.org get deployed
that includes the code from fedora-infra/anitya#74.

Auto add new packages.

---

fedmsg.d/hotness-example.py
hotness/consumers.py

And we define what a rawhide build is in the config.
This will be, like so many other things, a PITA in that when mass branch
time comes along, we'll have to remember to go into the hotness config
and update the suffix to the new rawhide suffix.  Such is life (if we
had a releng microservice that made available what the rawhide tag and
suffix was.. that would be awesome.  We should write that).
This fixes #14.

Only followup on rawhide builds.

---

yum-config

This should fix #16.
I thought it was going to require modification to
``hotness.repository.build_nvr_dict``, but local tests indicate that no changes
are required.

Use the kojira repos to get the latest rawhide info.

---

fedmsg.d/hotness-example.py
hotness/buildsys.py

We get lots of errors every now and then from hotness, mostly from failures to
automatically bump the spec and build the srpm.  Most of these are things we
can't do anything about, so no need to email us every day about it.

Suppress some errors from rpmbuild and friends.

---

fedmsg.d/hotness-example.py

This is just a reminder that things may have changed either in the Fedora
packaging guidelines or upstream and that both might need to be adjusted.
Text from spot at:
https://lists.fedoraproject.org/pipermail/legal/2015-February/002577.html

Note on the default message posted on bugzilla about packaging and legal changes

---

hotness/helpers.py

Which is sometimes prefixed on github version tags.
Fixes fedora-infra/anitya#102

Strip leading v.

---

hotness/buildsys.py
hotness/bz.py
hotness/consumers.py

Also, propagate srpm-creation and koji-kickoff errors to the ticket, instead of
emailing sysadmin-datanommer.
Almost always, this is an error in the specfile and I'd like to make the
packager(s) aware of that since I can't really do anything about it myself.

Create and attach patches to bz tickets we file.

---

hotness/anitya.py
hotness/consumers.py

It is possible for an anitya project to be mapped to two or more Fedora
packages.  In these cases we will now check the monitoring flag of *each*
one of those packages (not just whichever one appears first in the
list) and then file bugs for each of those packages that **do** want
bugs to be filed.
Fixes #33.

Handle multiply mapped anitya projects.

---

hotness/bz.py

When a Bugzilla attachment is flagged as a patch, Bugzilla
enables some extra UI features like diff display.

mark patches as such when attaching them in Bugzilla

---

hotness/anitya.py

The /login/fedora link may always just redirect the user silently.
Helps with #56, other part of the fix is in anitya.
Signed-off-by: Patrick Uiterwijk <puiterwijk@redhat.com>

Use the root url to check for logged in state

---

hotness/bz.py
hotness/consumers.py

This fixes #17.
With this code, we'll report successful rawhide builds (mostly) once.
Before, if there were many successive rawhide builds, we would report on
each one in the ticket, resulting in perhaps unwanted spam.  Here, we
check if the latest comment on the ticket was from the-new-hotness and
if it was about a successful rawhide build, then don't follow up with
another comment.
However, we will follow up a second time if, for some reason, the latest
comment is not from us.  We'll assume that that means there is some
abnormal situation with the ticket with respect to which it makes sense
to follow up about this new build.  For instance:
- A package maintainer has commented on the bug that something is screwy
and needs to be fixed, in which case our followup is relevant.
- Bodhi …

Report successful rawhide builds (mostly) once.

---

hotness/anitya.py
hotness/consumers.py

This should fix #46 and #65.
Sometimes, a new package added to Fedora pkgdb doesn't have an upstream_url
off the bat.  We already guard against that and avoid trying to update
anitya with that empty information.
This new code responds when the pkgdb weekly cronjob goes through and
updates the upstream_url field from a scan of the .spec/srpm information.
Since packagers have indicated that a package has a new upstream url, we
use that to update anitya's homepage information, and potentially map
packages to projects for the first time.
Also, silence some BeautifulSoup warnings.

Handle pkgdb.package.update messages.

---

hotness/consumers.py

We renamed the definition of this and we renamed one other usage, but we forgot this spot.  Getting traceback emails about it.

Rename this to match the function definition.

---

hotness/consumers.py

In the 0.6.0 release, we added some functionality that was meant to
reduce spam from the-new-hotness.  It would check the last posted
comment on a ticket it was about to comment on, and if the last
commenter was the-new-hotness, and if it was a build comment, but it
would just abort and not post another one.  This was meant to avoid
situations where someone is doing scratch builds of a package over and
over again, and hotness just sits there spamming their tickets.
There's an unanticipated scenario though:
commenter was the hotness, commenting about a build**, so it does
nothing.
We want that last comment to actually go through, but the current code
makes it abort.
The commit in this pull request changes it so that it won't make the
last comment *only if* the preceding comment was about …

Be a little more aggressive with real build comments.

---

hotness/anitya.py

Kinda ugly here, but login with release-monitoring.org broke when we
added a search form to every page there.
Hotness would try to scrape each page for a form, and then extract the
csrf_token from that form.  Except now, there are **two** forms on every
page, so that scraping broke.
This code updates each attempt at that to look explicitly for the form
it is interested in.

Fix release-monitoring.org html scraping.

---

hotness/anitya.py
the-new-hotness.spec

Fixes #89.
Running this locally, I was able to get my copy of hotness to create the entry:  https://release-monitoring.org/project/8436/

Allow mappings for npmjs.com as well as npmjs.org.

---

hotness/consumers.py

This should solve the problems that @phracek hit trying to test
the-new-hotness locally.
The problem is that:
- the-new-hotness has a list of topics it listens to, hardcoded to prod.
- when you replay a message with ``fedmsg-dg-replay`` it constructs a
new topic for the replayed message, using your local settings (dev
settings).
- even when you switch your local environment settings from dev to prod,
the anitya topics have a different *prefix* -- org.release-monitoring
instead of org.fedoraproject.
This gets around all that by (at startup time) checking to see if you're
in a dev environment, and if so, it rewrites the topics that
the-new-hotness is *listening* for and adds some appropriate ones so
that fedmsg-dg-replay will work.  This shouldn't affect our prod or stg
setups at all.

Rewrite topics to handle development mode.

---

hotness/buildsys.py

Any calls to ``log.error`` or ``log.exception`` will generate an email
to the admins of the-new-hotness.  Those are very useful, but if we get
them for non-urgent situations, it can inadvertently train us to not pay
attention to the emails over time.
So, I'd like to propose that we *demote* this log statement to a
warning.  What do you think @phracek?  Should it be kept as an error?

Make this log statement less verbose.

---

hotness/bz.py

Signed-off-by: Petr Hracek <phracek@redhat.com>
The fix should detect if file exists and is not empty.
This is not relevant only for rebase-helper case but general, I guess.
But of course, rebase-helper is going to be updated so that it provides logs which exists and are not empty.

Fixes #107: Detect if file exists or is not empty

---

hotness/consumers.py

I'd like @phracek to review this one before it gets merged since it
depends on the structure of the output from rebase-helper.  We found an
erroneous instance like this in #106 and I'm not sure if this is the
same kind of situation or not.
See https://github.com/fedora-infra/the-new-hotness/pull/106#discussion_r55363099

Correct another instance of mis-used six.iteritems().

---

hotness/consumers.py

... so let's put one in here to keep it consistent.  Other code raises a
traceback like the following without this change:
```python
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/moksha/hub/api/consumer.py", line 191, in _work
self.consume(message)
File "/usr/lib/python2.7/site-packages/hotness/consumers.py", line 156, in consume
self.handle_buildsys_scratch(msg)
File "/usr/lib/python2.7/site-packages/hotness/consumers.py", line 375, in handle_buildsys_scratch
self._update_tasks(task_id, state)
File "/usr/lib/python2.7/site-packages/hotness/consumers.py", line 736, in _update_tasks
bz, new_state, new_version, package = self.new_triggered_task_ids[task_id]
ValueError: need more than 2 values to unpack
```

This dict expects a 4-tuple everywhere else in the code.

---

hotness/consumers.py

Signed-off-by: Petr Hracek <phracek@redhat.com>

Fix #113 Text in bugzilla has to be clear.

---

hotness/consumers.py

We're in an exception-handling block here, and, depending on where in the
previous block the exception was raised it is possible that the ``tmp``
directory does not even exist.  So, we have to guard against that and log a
warning.

Handle OSError from 'rm'.

---

hotness/consumers.py

This should fix #95.
If rawhide matches upstream, we'll just be silent instead of pestering
maintainers about pkgdb monitoring being turned off.

Check if rawhide_version == upstream_version first.

---

README.rst

Just for readability in the terminal.

Some README tweaks.

---

devel/ansible/roles/hotness-dev/files/fedmsg.d/relay.py
devel/ansible/roles/hotness-dev/tasks/main.yml
fedmsg.d/base.py
fedmsg.d/hotness-example.py
fedmsg.d/ssl.py
hotness/anitya.py
hotness/buildsys.py
hotness/bz.py
hotness/consumers.py
hotness/helpers.py
setup.py
tests/test_helpers.py
tests/test_style.py

The tests were using nose and not the standard unittest module. This
changes that and the tests are now runnable by using `python setup.py
test`. This also fixes all PEP8 violations found by the new style test.

Change the tests to use unittest and add style check

---

fedmsg.d/hotness-example.py
hotness/consumers.py

By default, requests does not have a timeout for HTTP requests. This can
cause the application to hang indefinitely if the server never
responses.

Add timeouts to HTTP requests

---

hotness/buildsys.py

Starting with *rebase-helper* 0.8.0-3, `Application.setup()` method
returns more values than before. To remain compatible with all
versions of *rebase-helper*, avoid assigning returned values
to variables, pass them directly to `Application` constructor instead.

Do not assign unpacked result of Application.setup() to variables

---

fedmsg.d/logging.py
hotness/anitya.py
hotness/buildsys.py
hotness/bz.py
hotness/consumers.py

Previously, logs nearly all came from the "fedmsg" logger, which is very
confusing. This configures logging for the hotness package and gives
each module its own logger. The timestamp has also been removed by
default since journald keeps timestamps for us. It's easy to add back,
though, and the method is documented in fedmsg.d/logging.py
The old logs looked like:
[2016-12-06 16:58:28][    fedmsg    INFO] Handling koji...
The new logs look like:
[hotness.consumers INFO] Handling koji...

Modules now log using their own loggers

---

devel/ansible/roles/hotness-dev/tasks/main.yml
fedmsg.d/hotness-example.py
hotness/buildsys.py
tests/test_buildsys.py

The configuration provided in fedmsg.d/ indicates that 'hotness.koji'
accepts a 'userstring' key that is a tuple of (<name>, <email>). However
the code expects it to be a string.
This modifies hotness/buildsys.py to handle both cases and document the
expected type for this key.

Update usage of the 'userstring' config

---

devel/ansible/roles/hotness-dev/tasks/main.yml
hotness/buildsys.py
hotness/consumers.py
the-new-hotness.spec

This removes the dependency on rebase-helper in the-new-hotness. It also
fixes several of the commands that the-new-hotness shells out to which
depended on git to have a user configured. Finally, it also gets rid of
the 'userstring' setting in favor of a 'email_user' tuple which makes
configuring git with an author simpler.
Fixes #145

Remove rebase-helper

---

devel/ansible/roles/hotness-dev/files/fedmsg.d/hotness.py
docs/dev-guide.rst
fedmsg.d/hotness-example.py
hotness/buildsys.py

Koji requires Kerberos authentication now, so this switches
the-new-hotness to use that now.

Update the-new-hotness to use Kerberos authentication

---

hotness/buildsys.py

If the git clone fails for whatever reason, it removes the target
directory. The finally block is just supposed to make sure the directory
is gone and shouldn't have a problem if it already is gone.

Gracefully handle removing a directory that's already gone

---

hotness/buildsys.py
hotness/consumers.py
hotness/exceptions.py
hotness/tests/test_buildsys.py

This improves the error reporting for problems found while fetching the
specfile sources. It should now be more clear to end users what went
wrong and why, and things they can do to improve their specfiles.
Fixes #157, #158, and #160

Rework the buildsys source fetching

---

hotness/anitya.py
hotness/tests/test_anitya.py

This should resolve #116 (and #100). I implemented only rubygems- prefix support ATM, not sure how exactly other ecosystems works ...
Please note I did not tested the PR at all. I tried to go with Vagrant, but I gave up as soon as it required additional dependencies on my computer (I stumbled up on this already for second time already. Why should I have installed anything except Vagrant on my computer? I thought that Vagrant should shield me of all this).

Detect backend using package name prefix.

---

hotness/buildsys.py
hotness/consumers.py

At the moment, hotness shells out a lot and any time something goes
wrong a base ``Exception`` is raised. This needs to be re-written, but
in the meantime, this will at least let users know when and why an SRPM
failed to build.
Additionally, the generic exception message has been changed because it does actually email me for all the errors.
There aren't any tests (for which I am ashamed), but I want to re-write all this code and the only thing the tests could really do at the moment are assert I'm shelling out and ``Exception`` is raised. 😞 
fixes #171

Report SRPM build errors to users

---

hotness/bz.py

The latest python-bugzilla changed the default value for
bug_autorefresh, which causes it to not fetch bugzilla fields you access
if it wasn't part of the query. This breaks the-new-hotness because the
queries don't include all the fields we use. This turns the old behavior
back on
https://github.com/python-bugzilla/python-bugzilla/blob/v2.1.0/NEWS.md
fixes #179 

Enable the old python-bugzilla behavior for autorefresh

---

hotness/buildsys.py
hotness/consumers.py

This uses the standard library check_output API and handles any
exception it raises in a single location.
fixes #180

Use subprocess check_output for all commands

---

hotness/buildsys.py

I find the current error message when Source URLs are local ("One or more of the specfile's Sources is not a valid URL so we cannot automatically build the new version for you.  Please use a URL in your Source declarations if possible.") unnecessarily vague.  This patch lists (all) invalid URLs directly in the comment instead.
I only tested this patch in an isolated way, so I'm not sure whether for example the "layout" would survive being fed to Bugzilla, but rather than figuring that out myself I'll leave it to someone more knowledgeable :-).

List invalid Source URLs when failing

---

CHANGELOG.rst
devel/ansible/roles/hotness-dev/files/fedmsg.d/hotness.py
devel/ansible/roles/hotness-dev/files/motd
fedmsg.d/hotness-example.py
hotness/bz.py
hotness/tests/test_bz.py

This commit adds support for bugzilla API key. This should help prevent
losing session when using username and password.

Add bugzilla API key

---

CHANGELOG.rst
hotness/consumers.py
hotness/tests/test_consumers.py
hotness_schema/hotness_schema/messages.py
hotness_schema/hotness_schema/tests/test_messages.py

This should fix the issue with fedmsg_meta_fedora_infrastructure. Which
had trouble parsing the current messages because of the missing values
in trigger object.
I used the same logic for the summary methods as in [fedmsg_meta_fedora_infrastructure](https://github.com/fedora-infra/fedmsg_meta_fedora_infrastructure/blob/develop/fedmsg_meta_fedora_infrastructure/hotness.py).
Fixes #224 

Fix hotness fedora messaging schema

---

CHANGELOG.rst
hotness/buildsys.py
hotness/tests/test_buildsys.py

In python 3.7 it looks subprocess module is now returning binary string
instead of normal string.

Expect binary string instead str

---

hotness/tests/test_consumers.py

When AMQP server is not available (CI) these tests will fail when
fedora messaging publish method is called.
This fixes failing tests in #249 

Mock publish method to prevent fail

---

CHANGELOG.rst
hotness/consumers.py
hotness/tests/request-data/hotness.tests.test_consumers.TestConsumer.test_handle_anitya_version_update_bugzilla_error
hotness/tests/test_consumers.py

This should prevent issue when the-new-hotness is stuck on one message
when bugzilla issue is encountered. Now it should respond with NACK and
return the message back to RabbitMQ queue.

Nack fedora message when bugzilla error happens

---

.coveragerc
CHANGELOG.rst
tox.ini

Lower coverage threshold to 50% to make tests pass, but add diff
coverage rule for 100%. This means that every new code must be covered
by tests.

Coverage changes

---

hotness/buildsys.py
hotness/tests/test_buildsys.py
hotness/tests/test_consumers.py

I have added some unit tests for the `buildsys.Koji` module: they mostly rely on mocking function calls and I am not 100% happy about them currently (as they are not really "deep") but I don't know a better way how to add tests without running a fully fledged integration test suite.

Increase test coverage

---

.readthedocs.yml
docs/conf.py
setup.py

koji isn't needed to build the documentation and it's being mocked on docs/conf.py. I'm skipping the dep only on rtd. Also, adding a configuration file, so it's easy to configure the build.
Closes #264

Fix rtd build

---

hotness/helpers.py
hotness/tests/test_helpers.py

Modest increase to the test coverage of `helpers.py` (and shameless Hacktoberfest contribution). The resulting tests in turn produced the following changes:
- `rpm_max` and `upstream_max` have been updated to use sort `key` keyword argument instead of the non-existent in Python 3 `cmp` keyword argument, see e4bf65f.
- An unreachable section of `split_rc` was removed, see 77dcf15.
- `upstream_cmp` was changed to match the behavior described in a comments, and tested with the additional tests. See 19f70fe and 2e2c89b. This should be double-checked for correctness.

Increase test coverage of helpers.py

---

CHANGELOG.rst
setup.py
tox.ini

Because rpm dependency no longer supports python 3.5 remove python 3.5
support.

Drop python 3.5 support

---

hotness/helpers.py
hotness/tests/test_helpers.py

`url_prefix` check for empty string was removed as the code was unreachable. Since the `glob_pattern` has a minimum of two required `/` characters, there was no way for an url with less than 2 characters to match `glob_pattern`, so the `url_prefix` could never be an empty string.

Add expand_subdirs test

---

devel/ansible/roles/hotness-dev/tasks/main.yml
hotness/helpers.py
hotness/tests/test_helpers.py
requirements.txt
tox.ini

StringIO has been replaced with io.StringIO, the former no longer exists in Python3.
This adds pycurl as an explicit requirement. pycurl is now required to be available in the tox environment, which in turn requires both libcurl-devel and openssl-devel installed in the vagrant environment. pycurl is told to use the correct ssl library by setting the PYCURL_SSL_LIBRARY in tox.ini.

Fixes and tests for helpers.secure_download

---

hotness/helpers.py
hotness/tests/test_helpers.py

Change StringIO.StringIO to io.StringIO.
Change urllib.urlopen to urllib.request.urlopen.
Add tests for helpers.get_html.

Update helpers.get_html to work with Python 3

---

CHANGELOG.rst
config/config.toml.example
devel/ansible/roles/hotness-dev/files/config.toml
fedmsg.d/hotness-example.py
hotness/config.py

Change the links to the update policy to point to the fedora docs site instead of the wiki.

Change links to update policy

---

CHANGELOG.rst
hotness/buildsys.py
hotness/bz.py
hotness/config.py
hotness/consumers.py
hotness/tests/test_bz.py
hotness/tests/test_config.py

This fix is rather complex, so I split it to smaller parts:
1) Add recursive load of config dictionaries, this will ensure that
every config option we know will be available and we don't end up
with crash on empty dictionary
2) As direct reaction to the above default case sensitivity was changed
to lower, because this caused issues when passing arguments as dictionary to
3rd party libs
3) The copy of the config was changed to deep copy to also copy internal
dictionaries

Fix crash on empty config section

---

hotness/consumers.py
news/316.bug
news/318.bug

Fedora changed the master branch to rawhide. This change should fix the
issue related to this change, when package was considered retired,
because there was no master branch.
Also remove the news file, which was forgotten in latest release.
Fixes #318

Handle master -> rawhide branch change

---

hotness/builders/koji.py
tests/builders/test_koji.py

When testing #276 on staging issue with patch creating was discovered.
This is the fix for "[Errno 2] No such file or directory" happening on
koji builder.

Fix patch file handling in koji builder

---

hotness_schema/hotness_schema/messages.py
hotness_schema/hotness_schema/tests/test_messages.py
news/330.bug

When reason for the update.drop message is Anitya, it means that Anitya
doesn't have mapping for the package. Use the project name instead for
creating summary of the package.
Fixes #330

Fix error when creating update.drop message

---

hotness/builders/koji.py
news/286.feature
tests/builders/test_koji.py

This will change the checksum from SHA256 to SHA512 and
will also detect identical files between new sources or
old sources.
Closes #286

Add SHA512 values to error message about same sources

---

Containerfile.dev
docs/dev-guide.rst
news/PR340.dev

I tested the container environment on RHEL 8 and faced with following errors:
- Somehow getting `pip not found` and `python not found`
- Healthchecks are not recognized by podman, so we need to either comment out `depends_on` block of `hotness` service or all the `healtcheck` blocks.
On this PR, I provide Containerfile compatibility for podman, and updated the docs for letting the contributors know that they should comment `depends_on` or `healtcheck` blocks for using podman.

Provide podman compatibility

---

config/config.toml.example
hotness/builders/koji.py
hotness/config.py
hotness/exceptions/builder_exception.py
hotness/hotness_consumer.py
hotness/responses/response_failure.py
news/333.feature
tests/builders/test_koji.py
tests/exceptions/test_builder_exception.py
tests/responses/test_response_failure.py
tests/test_config.py
tests/test_hotness_consumer.py

This commit adds additional attributes to ResponseFailure class.
* std_out and std_err for BuilderException - this will allow us to print
stdout and stderr from CalledProcessError to bugzilla issue
* output for BuilderException - this will help us to be able to print
build link in the future
* traceback - to be able to print traceback in the bugzilla ticket so
packagers could report the issue
This information are added as comment to bugzilla ticket whenewer the
build fails.
The build failure now also contains a link to the-new-hotness issue
tracker, so it will be easier for packagers to report new issues in the
future.
Closes #333

Show stdout + stderr from CalledProcessError

---

hotness/hotness_consumer.py
news/332.bug
tests/test_hotness_consumer.py

Currently the-new-hotness didn't saved the koji build id when any
failure happened during the build use case. This caused that when the
build fedora message arrived it was not recognized by the-new-hotness.
This commit is saving the koji build id to cache even when there is
failure during the build use case, but the build successfully started.
Fixes #332

Save koji id even if build use case fails

---

hotness/builders/koji.py
hotness/exceptions/__init__.py
hotness/exceptions/base_exception.py
hotness/exceptions/builder_exception.py
hotness/exceptions/http_exception.py
hotness/exceptions/notifier_exception.py
hotness/exceptions/patcher_exception.py
hotness/hotness_consumer.py
hotness/responses/response_failure.py
news/345.bug
news/353.dev
tests/builders/test_koji.py
tests/exceptions/test_base_exception.py
tests/exceptions/test_builder_exception.py
tests/exceptions/test_download_exception.py
tests/exceptions/test_notifier_exception.py
tests/exceptions/test_patcher_exception.py
tests/responses/test_response_failure.py
tests/test_hotness_consumer.py
tests/use_cases/test_insert_data_use_case.py
tests/use_cases/test_notify_user_use_case.py
tests/use_cases/test_package_check_use_case.py
tests/use_cases/test_package_scratch_build_use_case.py
tests/use_cases/test_retrieve_data_use_case.py
tests/use_cases/test_submit_patch_use_case.py

Create a BaseHotnessExceptions that will define the default values for
properties and methods expected by ResponseFailure class. This will help
with inconsistency when working with exceptions.
* Adds new BaseHotnessException
* Moves the message construction to BuilderException
* Adds inheritance of the BaseHotnessException to other exceptions
* Removes unecessary methods from ResponseFailure class
* Add new method for value in ResponseFailure class, this will return
the value in exception
* Removes message construction from HotnessConsumer, to prevent crashes
when DownloadException is returned instead of BuilderException
Fixes #345
Fixes #353

Unify exceptions

---

.zuul.yaml
news/391.bug
setup.py
tox.ini

Python 3.6 is now EOL. Drop it from the-new-hotness.
Closes #391

Drop support for python 3.6

---

.zuul.yaml

Anitya jobs were migrated from pod-python-f35 label to cloud-fedora-35 and we
need to adjust to this change.

Add krb5-devel dependency to CI jobs defined in Anitya

---

config/config.toml.example
devel/ansible/roles/hotness-dev/files/config.toml
hotness/config.py
hotness/hotness_consumer.py
hotness/notifiers/bugzilla.py
hotness/patchers/bugzilla.py
news/401.dev
requirements.txt
tests/notifiers/test_bugzilla.py
tests/patchers/test_bugzilla.py
tests/test_config.py
tests/test_hotness_consumer.py

Remove username and password authentication from Bugzilla code.
Change minimal version of python-bugzilla to 3.2.0.
Introduce reporter_email instead of username for searching.
See announcement e-mail for more info:
https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/U3PQNCLKA3R6GA2UI2EZP2OT4VAKVHBI/
Closes #401.

Prepare for change in Bugzilla API

---

.zuul.yaml
news/PR405.dev
setup.py
tox.ini

With introduction of Sphinx 4.4.0 the dependencies couldn't be satisfied on
Python 3.7, so it's probably time to remove it.
```
The conflict is caused by:
flake8 4.0.1 depends on importlib-metadata<4.3; python_version < "3.8"
pytest 6.2.5 depends on importlib-metadata>=0.12; python_version < "3.8"
sphinx 4.4.0 depends on importlib-metadata>=4.4; python_version < "3.10"
```

Remove python 3.7

---

tests/notifiers/test_bugzilla.py
tests/patchers/test_bugzilla.py
tests/test_hotness_consumer.py

The pytest 7.0.0 doesn't work well with mock.patch decorators in setup methods.
This commit changes them to with statements.

Fix pytest 7.0.0 errors

---

.zuul.yaml
dev-requirements.txt
hotness/builders/koji.py
hotness/common/rpm.py
hotness/config.py
hotness/databases/cache.py
hotness/domain/package.py
hotness/exceptions/builder_exception.py
hotness/hotness_consumer.py
hotness/notifiers/bugzilla.py
hotness/notifiers/fedora_messaging.py
hotness/patchers/bugzilla.py
hotness/requests/request.py
hotness/responses/response_failure.py
hotness/validators/pdc.py
news/PR407.dev
tests/validators/test_pdc.py
tox.ini

This PR will enable and fix all issues with mypy in CI.

Enable mypy in CI

---

.readthedocs.yml
.zuul.yaml
news/408.dev
tox.ini

This commit will add python 3.10 to tox and zuul CI. It also updates readthedocs
configuration to python 3.10.
Closes #408

Add support for Python 3.10

---

.readthedocs.yml

Use build.tools.python instead of python.version. python.version was deprecated.
See https://docs.readthedocs.io/en/stable/config-file/v2.html#python-version

Add build configuration for readthedocs

---

container-compose.yml
dev-requirements.txt

On Fedora 36 the podman-compose up is failing with multi-service deployment when
network_mode is set to host. Setting the specific ports makes the ports
available in both host and hotness container.

Define ports instead of using network_mode: host

---

.zuul.yaml

Zuul jobs were migrated from Anitya to Zuul repository and this is causing
issues when trying to run the jobs in hotness, because of the name change.
See https://github.com/fedora-infra/anitya/pull/1333 and https://pagure.io/fedora-infra/zuul/pull-request/4

Use the jobs migrated from Anitya

---

README.rst

It would be nice to have some quick indication of the version and documentation
status on main page of the project and this is a good option.

Add PyPi and ReadTheDocs banners to README

---

config/config.toml.example
devel/ansible/roles/hotness-dev/files/config.toml
docs/user-guide.rst
hotness/config.py
hotness/hotness_consumer.py
hotness/validators/pagure.py
news/230.feature
tests/fixtures/anitya.project.version.update.v2/fedora_mapping.json
tests/fixtures/anitya.project.version.update.v2/no_mapping.json
tests/test_hotness_consumer.py
tests/validators/test_pagure.py

This new message topic sends multiple versions at once instead of just one new
version. This commit will update hotness to be able to notify user about other
releases if they are found by Anitya.
It also adds support for new dist-git monitoring options, which allows
maintainers to get notifications about every version that is retrieved by
Anitya, even if it's not considered latest.
Closes #230

Add support for Anitya ProjectVersionUpdatedV2 message

---

hotness/validators/mdapi.py
news/437.bug
tests/validators/test_mdapi.py

When the version containing dist tag was reported by Anitya. Hotness erroneously
notified maintainer about this version even if the version wasn't really newer.
For example upstream version 10.1-1 was considered newer than version 10.1-1 in
Fedora.
The fix removes the dist tag before comparison.
Fixes #437

Fix for dist tag notification

---

Containerfile.dev
devel/ansible/roles/hotness-dev/tasks/main.yml

Remove schema from both podman and vagrant devel environments.
Clean up packages for vagrant.
Closes #326

Clean devel environments

---

config/config.toml.example
devel/ansible/roles/hotness-dev/files/config.toml
hotness/config.py
hotness/hotness_consumer.py
news/324.feature
tests/test_hotness_consumer.py

Currently the notification is missing the link to fedora package repository
which contains settings for the monitoring itself.
This commit is adding the link to bugzilla notification.
Closes #324

Add link to repository to bugzilla notification

---

hotness/exceptions/builder_exception.py
news/456.bug
tests/exceptions/test_builder_exception.py

Hotness didn't checked the build_id variable for value when creating error
message and erroneously reported that the build already started.
This commit is adding the check for zero together with new test.
Fixes #456

Use the correct error message before build starts

---

Containerfile.dev
config/config.toml.example
container-compose.yml
dev-requirements.txt
devel/ansible/roles/hotness-dev/files/config.toml
devel/ansible/roles/hotness-dev/tasks/main.yml
devel/ansible/roles/hotness-dev/tasks/redis.yml
docs/admin-guide.rst
docs/ca-design.rst
hotness/config.py
hotness/databases/__init__.py
hotness/databases/redis.py
hotness/hotness_consumer.py
news/323.feature
requirements.txt
tests/databases/test_redis.py
tests/test_config.py
tests/test_hotness_consumer.py

Redis will be used instead of local cache, which will allow us to easily
increase the number of hotness instances without worries about losing data about
builds.
Closes #323

Add support for redis

---

Containerfile.dev
container-compose.yml
news/PR465.dev

Also add packages that are needed to get kerberos token for fedora.

Update container dev environment to Fedora 36

---

Containerfile.dev
news/PR472.dev

There were a few required packages missing in container dev environment. This
commit will add them.

Add missing packages to podman dev environment

---

hotness/builders/koji.py
news/PR473.bug
tests/builders/test_koji.py

The spectool output is now changed to
```
Downloading: https://www.imagemagick.org/download/releases/ImageMagick-6.9.12-51.tar.xz
100% of   8.7 MiB |####################################################################################################################################################################################| Elapsed Time: 0:02:30 Time:  0:02:30
Downloaded: ImageMagick-6.9.12-51.tar.xz
```
Which caused that the comparing of sources were done incorrectly.
This patch fixes that behavior.

Handle the correct output line for spectool

---

docs/dev-guide.rst

Hotness is now migrated to OpenShift 4 instance in Fedora Infra, reflect this
change in documentation.

Change the staging env link to OCP4

---

.github/dependabot.yml
.mergify.yml
news/PR516.other
renovate.json

The renovate looks like a better alternative to dependabot, which is no longer actively maintained.

Migrate from dependabot to renovate

---

.readthedocs.yml

The readthedocs build environment has problem to handle all the dependencies, so let's install just the development ones as we did before moving to poetry.

Fix the documentation build on readthedocs

---

hotness/builders/koji.py
hotness/hotness_consumer.py
news/547.bug
tests/builders/test_koji.py
tests/test_hotness_consumer.py

Fix the error message returned from koji module on spectool failure + add patch to bugzilla ticket when already available to see what hotness did when updating specfile.
Fixes #547

Fix: Error message from Koji is wrong

---

hotness/hotness_consumer.py
news/533.bug
tests/test_hotness_consumer.py

Previously we changed the bugzilla ticket title when we received a new version from Anitya, but this doesn't need to be the latest upstream version all of the time. So it's better to keep the latest upstream in title instead.
Fixes #533

Don't change title of the bugzilla ticket when version is not latest

---

.zuul.yaml
tox.ini

Tox changed the whitelist to allowlist and break the tests. Let's fix that and hope that this play with words doesn't happen in the future.

Change whitelist to allowlist

---

docs/user-guide.rst
news/558.other

There is now possibility to file pull requests thanks to the Packit Team and the-new-hotness. Let's document this in the-new-hotness documentation, so users know about it.

Document the way to file pull requests

---

hotness/builders/koji.py
news/564.bug
tests/builders/test_koji.py

DownloadException doesn't have any additional values with it, so it doesn't carry the spec file diff that is already created. So let's raise BuilderException instead when DownloadException should be raised.
Fixes #564

Attach spec file diff when DownloadException is raised

---

hotness/builders/koji.py
news/557.bug
tests/builders/test_koji.py

The koji uploadWrapper sometimes fails with GenericError, let's retry the upload if this happens.
Fixes #557

Add retry when uploading sources to koji
