fedora-infra/the-new-hotness

hotness/consumers.py
As introduced in mokshaproject/moksha#25.
Fixes #2.
=> Use the multiple-topics feature from moksha.hub-1.4.4

hotness/bz.py, hotness/consumers.py, setup.py
..not just scratch ones.  Fixes #4.
=> Comment on real koji builds.

hotness/consumers.py
Currently, we fail to kick off scratch builds somewhat often.
Sometimes:
- The spec file is formatted very strangely, and rpmdev-bumpspec doesn't
know what to do.
- The SOURCES are not downloadable, and spectool doesn't know what to
do.
- The modified file is not even buildable into an SRPM for koji, so
rpmbuild doesn't know what to do.
- Koji is not reachable over the network because it's down or something,
so the koji client api doesn't know what to do.
In all of these cases, we currently generate two emails:
- First, with a ``log.error()`` statement **inside**
``buildsys.handle(...)``.
- Second, with an exception that bubbles up to the fedmsg code above us.
This code catches the exception and just logs it as a **warning** since,
it's really not a problem with our code, but instead just …
=> Suppress errors.

hotness/consumers.py
See this one, where we posted about a rawhide build, but the bug was
already closed:  https://bugzilla.redhat.com/show_bug.cgi?id=969399#c67
=> Only followup on bugs that are not already closed.

fedmsg.d/hotness-example.py, hotness/buildsys.py, hotness/repository.py
=> Generate a nicer changelog for the scratch task srpm.

hotness/anitya.py
This version_url contains the owner/project information that is required by
anitya to automatically retrieve version information.
=> For github backend, if the homepage is on github, specify the version_url to use

hotness/repository.py
I think I removed this by mistake in 4f300982 when I was doing some
debug work.
=> This should actually be cached.

hotness/buildsys.py
=> Compare sum of new and old tarball.

hotness/anitya.py, hotness/consumers.py
And use those events as another opportunity to try and map stuff in
anitya.
Fixes #32.
Fixes #35.
=> Listen for pkgdb monitoring toggle events.

hotness/repository.py
Sometimes our cache is just out of date.
If we fail to find something, this forces a refresh.
Should fix #40.
=> Try twice to find the rawhide version of packages.

hotness/buildsys.py
This should fix #54.  I was able to duplicate the error locally and this
fixed it for me.
=> Fix fedpkg sources parsing.

hotness/bz.py, hotness/consumers.py
Fixes #52.
Tested with partner-bugzilla, see https://partner-bugzilla.redhat.com/show_bug.cgi?id=1105934
=> Follow up on FTBFS bugs.

hotness/bz.py
=> Match bugs also in the ASSIGNED state.

hotness/anitya.py
The only 'list index out of range' errors I see in the logs all come
from these code blocks.  I went looking for them while trying to fix
issue #43, but these code paths aren't related to that issue.
=> Be extra careful with anitya error panels.

hotness/bz.py, hotness/consumers.py
=> Mention scratch build results in review request tickets.

hotness/consumers.py
=> Don't act on packages that are retired.

hotness/consumers.py
And replace it with a warning in the logs.
I looked into all the error emails we got about this the last week, and
they're all reasonable situations.
- A new package was added to pkgdb after the Review process completed.
- hotness noticed that, and added the pkg to anitya.
- hotness forced an anitya check
- anitya published a fedmsg message that a new version was found
- hotness received that message and tried to compare that new upstream
version against the version in rawhide but... of course, no build had
completed in rawhide yet.  And even if it had in the tiny interval of
time that has elapsed so far, the rawhide repo would not have been
rebuilt for us to check.
So, we should assume that rawhide *will* be up to date with the latest
upstream at this point, since the package **just** …
=> Silence this error email.

fedmsg.d/hotness-example.py, hotness/bz.py, hotness/consumers.py
Fixes https://github.com/fedora-infra/anitya/issues/149
=> When sending a comment to bugzilla add a link to the project in anitya

hotness/buildsys.py, hotness/consumers.py, hotness/repository.py, setup.py, the-new-hotness.spec
I have finally implemented.
https://partner-bugzilla.redhat.com/show_bug.cgi?id=1259391 Especially from 13.1.2016
Feel free to send comments and I will correct it.
If something is wrong do not hesitate to contact me.
=> Rebase helper integration.

fedmsg.d/hotness-example.py, hotness/consumers.py, hotness/repository.py
Keep it simple, and just pass it in.
=> Remove pkg_manager detection.

hotness/repository.py
Hit this in staging.
I didn't hit the failure on my box because I was using dnf.
=> Handle repoquery differently for yum and dnf.

hotness/bz.py
valid only in case really attach.
Signed-off-by: Petr Hracek <phracek@redhat.com>
=> Fixes #110: This does not really fix the problem. Log about attaching is

hotness/consumers.py
Signed-off-by: Petr Hracek <phracek@redhat.com>
=> Check if dir exists before deleting

hotness/consumers.py
While testing current the-new-hotness code with local fedmsg instance I found a few issues in mdapi implementation.
@ignatenkobrain: Can you take a look at this?
=> Fix some bugs in mdapi implementation

.gitignore, Vagrantfile.example, devel/anitya_updates.py, devel/ansible/roles/hotness-dev/files/bashrc, devel/ansible/roles/hotness-dev/files/fedmsg.d/base.py, devel/ansible/roles/hotness-dev/files/fedmsg.d/hotness.py, devel/ansible/roles/hotness-dev/files/fedmsg.d/logging.py, devel/ansible/roles/hotness-dev/files/fedmsg.d/relay.py, devel/ansible/roles/hotness-dev/files/fedmsg.d/ssl.py, devel/ansible/roles/hotness-dev/files/hub.service, devel/ansible/roles/hotness-dev/files/motd, devel/ansible/roles/hotness-dev/files/relay.service, devel/ansible/roles/hotness-dev/tasks/main.yml, devel/ansible/vagrant-playbook.yml
This adds a Vagrant environment for developers. Documentation is in a
separate commit.
=> Add a Vagrant environment for the-new-hotness

hotness/buildsys.py, hotness/bz.py, hotness/consumers.py, the-new-hotness.spec
Be compatible with rebase-helper >= 0.8.
Do not attach logs from rebase-helper as patches.
=> rebase-helper fixes

hotness/consumers.py
This documents the fedmsg consumer class and the handler methods it
implements. There are still several undocumented public functions and
methods, but this covers all the incoming message types and the general
actions taken for each message.
=> Add documentation for the message handlers

dev-requirements.txt, requirements.txt, setup.py
=> Add a requirements.txt and dev-requirements.txt

devel/ansible/roles/hotness-dev/files/fedmsg.d/hotness.py, fedmsg.d/hotness-example.py
@puiterwijk noted several outdated URls while reviewing #147. This fixes
those outdated URLs.
=> Update configuration URLs

CHANGELOG.rst
=> Add a changelog for the 0.8.0 release

hotness/buildsys.py, hotness/consumers.py, setup.py, tests/test_buildsys.py
I did bad things and managed to break some tests without noticing. This
addresses all those issues
=> Fix tests I broke

CHANGELOG.rst
=> Update the changelog for 0.8.1

hotness/anitya.py
=> Add pypi.org to the backend mapping dictionary

hotness/buildsys.py
fixes #174
Signed-off-by: Randy Barlow <randy@electronsweatshop.com>
=> Fix a grammatical error in an error message.

.gitignore, hotness/consumers.py, hotness/tests/test_buildsys.py, hotness/tests/test_consumer.py, requirements.txt
Still in progress.  Started adding tests.
=> Port away from pkgdb.

devel/ansible/roles/hotness-dev/files/bashrc, devel/ansible/roles/hotness-dev/files/motd, devel/ansible/roles/hotness-dev/tasks/main.yml
This PR takes in consideration https://github.com/fedora-infra/the-new-hotness/pull/198 and https://github.com/fedora-infra/the-new-hotness/pull/197.
These two should be merged first.
=> Update vagrant container

Vagrantfile.example, devel/ansible/roles/hotness-dev/tasks/main.yml, hotness/consumers.py
* Update dev environment to use python3 packages where available
* Fix existing tests with python3
The tests are currently covering only 36% of actual code. So this PR doesn't mean, that the code is python3 compatible yet.
However I tried to import `hotness` module in python 3.6.6 and didn't got any SyntaxError, so this looks promising.
=> Preparation for python 3

.cico.pipeline, tox.ini
I've installed a pipeline shared library in the jenkins-fedora-apps master that will run tox for us. This adds a couple of things to make that possible.
=> CI, We should do some of that. 

README.rst
Provide users with an easy way to see the-new-hotness in action.
=> README: link to datagrepper

CHANGELOG.rst, tox.ini
=> Remove python 2 from tox

CHANGELOG.rst, hotness/buildsys.py, hotness/helpers.py, tox.ini
=> Add bandit to tox.ini

CHANGELOG.rst, config/config.toml.example, devel/ansible/roles/hotness-dev/files/config.toml, hotness/bz.py, hotness/tests/test_bz.py
Add reporter to bugzilla query
Fixes #234
=> Fix hijacking bugzilla issue

CHANGELOG.rst, hotness/buildsys.py, hotness/tests/test_buildsys.py
=> Fix missing user for fedpkg

CHANGELOG.rst, hotness/buildsys.py, hotness/tests/test_buildsys.py
=> Fix wrong parameter in fedpkg

CHANGELOG.rst, hotness/buildsys.py, hotness/tests/test_buildsys.py
=> Fix binary string error

CHANGELOG.rst, hotness/buildsys.py
=> Expect binary string when handling scratch build

CHANGELOG.rst, hotness/buildsys.py
=> Convert toml InlineTable to dict

CHANGELOG.rst, hotness/buildsys.py, hotness/tests/test_buildsys.py
=> Fix crash when curl returns 400+ error

docs/dev-guide.rst
=> Add release guide

.gitignore, Vagrantfile, devel/ansible/roles/hotness-dev/tasks/main.yml
=> Update vagrant environment to F30

CHANGELOG.rst, devel/ansible/roles/hotness-dev/tasks/main.yml
=> Fix deprecation warning in ansible

CHANGELOG.rst, hotness/consumers.py, hotness/tests/test_consumers.py
Signed-off-by: Pierre-Yves Chibon <pingou@pingoured.fr>
=> Retrieve the monitoring status from dist-git instead of fedora-scm-requests

CHANGELOG.rst, docs/conf.py
=> Fix docs building

CHANGELOG.rst, docs/conf.py
=> Mock rpm-py-installer

CHANGELOG.rst, docs/conf.py
=> Use autodoc_mock_imports

hotness/tests/test_helpers.py
Add a test for 100% coverage of `match_interval`.
=> Add tests for match_interval

CHANGELOG.rst, hotness/helpers.py, tox.ini
* Fix rpm module import
* Fix flake8 checking everything instead only hotness and schema
=> Fix failing tests

ca_design/design.md, ca_design/requirements.md
This design document could be in future used as foundation for clean
architecture implementation of the-new-hotness.
=> Add the-new-hotness design document

CHANGELOG.rst, hotness/anitya.py, hotness/bz.py, hotness/tests/test_helpers.py, requirements.txt
Hi, I'm just passing by and took a stab at what looks like an easy ticket. I used [vulture](https://pypi.org/project/vulture/) and this one-liner to help find these functions.
```
cd the-new-hotness
for i in $(vulture . 2>&1 | grep 'unused function' | awk '{print $4}' | sed "s/'//g"); do grep -r ${i}; done
```
Fixes #261
=> Removed unused functions

CHANGELOG.rst
=> Fix PR number

CHANGELOG.rst, hotness/anitya.py, hotness/tests/request-data/hotness.tests.test_anitya.ForceCheckTests.test_force_check_error, hotness/tests/request-data/hotness.tests.test_anitya.ForceCheckTests.test_force_check_success, hotness/tests/test_anitya.py
=> Clean and raise coverage for Anitya module

CHANGELOG.rst, devel/ansible/roles/hotness-dev/files/config.toml, hotness/config.py, hotness/consumers.py, hotness/tests/test_config.py, hotness/tests/test_consumers.py
=> Refactor config to use centralized defaults

CHANGELOG.rst, hotness/anitya.py, hotness/consumers.py, hotness/tests/test_anitya.py, hotness/tests/test_consumers.py, requirements.txt
=> Use anitya schema for fedora messaging

CHANGELOG.rst, hotness/bz.py, hotness/tests/test_bz.py
=> Fix crash on bugzilla bug update

CHANGELOG.rst, docs/conf.py
=> Fix RTD build

CHANGELOG.rst, Vagrantfile, devel/ansible/roles/hotness-dev/tasks/main.yml
=> Update vagrant environment to F32

CHANGELOG.rst, Vagrantfile, devel/ansible/roles/hotness-dev/tasks/main.yml, requirements.txt
=> Clean dependencies

CHANGELOG.rst, docs/dev-guide.rst
=> Update developer guide

hotness/buildsys.py, hotness/tests/test_buildsys.py
=> Fix formatting

requirements.txt
=> Make requirements less strict

hotness/buildsys.py, hotness/bz.py, hotness/consumers.py, hotness/helpers.py, hotness/tests/test_buildsys.py, hotness/tests/test_bz.py, hotness/tests/test_consumers.py
=> Fix formatting and failing test

hotness/anitya.py, hotness/consumers.py, hotness/tests/test_anitya.py, news/316.bug
=> Fix the issue with Anitya 1.0.0 API

hotness/patchers/bugzilla.py, hotness/use_cases/retrieve_data_use_case.py, hotness/use_cases/submit_patch_use_case.py, tests/patchers/test_bugzilla.py
Fixes for #276 deployment in staging.
=> Minor fixes for staging deployment

hotness/builders/koji.py
=> Fix info message for initiating koji build

docs/dev-guide.rst, news/338.dev
=> Sync issues with news

.mergify.yml, .zuul.yaml, ci/test-tox.yaml, dev-requirements.txt, news/309.dev, tox.ini
* Add .zuul.yaml
* Add ci folder
* Move some requirements from tox.ini to dev-requirements
* Update .mergify.yml
Closes #309
=> Migrate to Zuul

Containerfile.dev, Makefile, container-compose.yml, docs/dev-guide.rst
Applied same containerization techniques that have been used for Anitya
=> podman-compose instead of docker-compose for Podman

Vagrantfile, news/PR349.dev
=> Update vagrant to F34

.github/dependabot.yml
* Change interval to weekly
* Remove versioning strategy
=> Change the dependabot config to make it work again

hotness/builders/koji.py, hotness/notifiers/bugzilla.py, hotness/notifiers/fedora_messaging.py, hotness/patchers/bugzilla.py, tests/builders/test_koji.py, tests/notifiers/test_bugzilla.py, tests/notifiers/test_fedora_messaging.py, tests/patchers/test_bugzilla.py, tests/validators/test_mdapi.py, tests/validators/test_pagure.py, tests/validators/test_pdc.py
=> Don't call asserts inside with pytest.raises

.zuul.yaml
=> Update Zuul config

docs/ca-design.rst, docs/dev-guide.rst
=> Fix formatting in documentation

hotness/hotness_consumer.py, tests/test_hotness_consumer.py
=> Add explanation message when scratch build fails

devel/ansible/roles/hotness-dev/tasks/main.yml
Remove dependencies from playbook that are no longer needed.
=> Clean dependencies in playbook

.zuul.yaml, news/393.dev
=> Update pods in CI to Fedora 35

.zuul.yaml, ci/test-tox.yaml, dev-requirements.txt
=> Switch to zuul-worker from pod-python 

Containerfile.dev
=> Remove dependencies that are no longer needed from container

.mergify.yml
=> Fix the dependabot rule for mergify

config/config.toml.example, hotness/config.py, hotness/hotness_consumer.py, tests/test_config.py, tests/test_hotness_consumer.py
=> Fix the package version reported in the bugzilla header

config/config.toml.example
=> Fix syntax error in example config

Vagrantfile, container-compose.yml, devel/ansible/roles/hotness-dev/tasks/main.yml
=> Update dev env to F38

docs/dev-guide.rst, news/PR574.dev, poetry.lock, pyproject.toml
Update documentation to reflect this change
=> Add towncrier and tox to dev dependencies
